services:
  db:
    image: postgres:17
    container_name: bpm_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: bpm_primes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: bpm_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/bpm_primes_db

  frontend:
    build: ./frontend
    container_name: bpm_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from hot-reload
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # For hot-reload on Windows

volumes:
  postgres_data:
